/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testSquirrelName() {
        Squirrel squirrel = new Squirrel("Testy");
        assertEquals("Test", squirrel.getName());
    }

    @Test
    public void testNodeData() {
        Squirrel squirrel = new Squirrel("Node");
        Node node = new Node(squirrel);
        assertEquals("Node", node.getData().getName());
    }
}
